services:
    base:
        extends:
            file: "../base/compose.yml"
            service: "base"
    dev:
        depends_on:
            - "base"
        build:
            context: "."
            dockerfile: "Dockerfile"
            args:
                DEV_USER_USERNAME: dev-user
        volumes:
            - "../../:/workspace:cached"
            - "${HOME}/.ssh/:/home/dev-user/.ssh/:ro"
            - "${HOME}/.gitconfig:/home/dev-user/.gitconfig:ro"
        env_file:
            - "../../.devcontainer.env"
        command: /bin/sh -c "while sleep 1000; do :; done"
