services:
    base:
        extends:
            file: "../base/compose.yml"
            service: "base"
    dev:
        environment:
            DEV_USER_USERNAME: "dev-user"
        depends_on:
            - "base"
        build:
            context: "."
            dockerfile: "Dockerfile"
            args:
                DEV_USER_USERNAME: ${DEV_USER_USERNAME}
        volumes:
            - "../../:/workspace:cached"
            - "${HOME}/.ssh/:/home/${DEV_USER_USERNAME}/.ssh/:ro"
            - "${HOME}/.gitconfig:/home/${DEV_USER_USERNAME}/.gitconfig:ro"
        env_file:
            - "../../.devcontainer.env"
        command: /bin/sh -c "while sleep 1000; do :; done"
