services:
  devpod-dev:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
    volumes:
      - "..:/workspace:cached"
    env_file:
      - "devcontainer.env"
    command: /bin/sh -c "while sleep 1000; do :; done"
