services:
    dev:
        build:
            context: ".."
            dockerfile: ".devcontainer/Dockerfile"
        volumes:
            # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
            # mounts are relative to the first file in the list, which is a level up.
            - "..:/workspace:cached"
        env_file:
            - "../.env"
        command: '/bin/sh -c "while sleep 1000; do :; done"'
